### ISSUE TITLE
Missing File in the repo

### ISSUE THREAD

**Issue by nsankar** [biankabakullari/hlem-framework#1]
Hi @biankabakullari  The paper was pretty interesting to read. I tried running the code and got the import result_statistics as stat error shown below. The **result_statistics** file is missing in the repo. Can you please add it. Thanks

![image](https://user-images.githubusercontent.com/431890/201526657-873816a6-7b89-4540-9937-e98213de2e3a.png)

**Comment by biankabakullari** [comment]
Missing function was added
